apiVersion: v1
kind: Pod
metadata: 
  name: backup-mongodb
  namespace: mongodb
spec:
  serviceAccountName: mongo-service-account
  restartPolicy: OnFailure  
  containers:
  - name: backup-mongodb-full
    image: customs/mongobackup:latest
    env:
    - name: MONGO_URI
      value: mongodb://root:<mongodb-password>@mongodb-0.mongodb-headless.mongodb.svc.cluster.local:27017
    - name: MONGO_OPLOG
      value: "true"
    - name: MONGO_BUCKET_URI
      value: s3://<bucket-name>
      
